version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  database:
    networks:
      - app-tier
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=board-system
      - TZ=Asia/Seoul
    volumes:
      - ./mariadb:/var/lib/mysql
  app:
    networks:
      - app-tier
    container_name: node-app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"    
    build:
      context: /home/mediatest/Desktop/app/board-server-webpack-dist
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    links:
      - database
    volumes:
      - /data/Shared/node/log:/root/node-app/log
      - /data/Shared/node/resources:/root/node-app/resources
    depends_on:
      - database
    environment:
      - TZ=Asia/Seoul