version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  database:
    networks:
      - app-tier
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=board-system
      - TZ=Asia/Seoul
    volumes:
      - ./mariadb:/var/lib/mysql
  phpmyadmin-db:
    restart: always
    depends_on:
      - database
    networks:
      - app-tier
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    links:
      - "database:db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Asia/Seoul
  redis:
    networks:
      - app-tier
    image: redis:6.0.3
    restart: always
    # hostname: "redis"
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    container_name: redis
    expose:
      - "6379"
  app:
    networks:
      - app-tier
    container_name: node-app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"    
    build:
      context: /home/media/Desktop/app/board-server-webpack-dist
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    links:
      - database
      - redis
    volumes:
      - /data/Shared/node/log:/root/node-app/log
      - /data/Shared/node/resources:/root/node-app/resources
    depends_on:
      - database
      - redis
    environment:
      - TZ=Asia/Seoul